theme: jekyll-theme-minimal
title: Jade001 Large Green Jade Dish 碧玉大盤
description: Collected by the Qianlong Emperor. <iframe src="https://drive.google.com/drive/folders/1oLlT5bWOFiDckklvRByhlNfVFwrMoNtx" title="Jade Text Comparisons"
logo: Jade001_Images/Jade001_NPMT_front.jpg


