theme: jekyll-theme-minimal
title: Jade001 Large Green Jade Dish 碧玉大盤
description: <div class="jp-Cell-outputWrapper">


<div class="jp-OutputArea jp-Cell-outputArea">

<div class="jp-OutputArea-child">

    
    <div class="jp-OutputPrompt jp-OutputArea-prompt">Out[4]:</div>

<div class="jp-RenderedHTMLCommon jp-RenderedMarkdown jp-OutputArea-output jp-OutputArea-executeResult" data-mime-type="text/markdown">
    <p><style>                           
    span.delete {color: #32a852; 
                 background-color: lavender;
                 font-size: 150%; 
                 margin: 0 3px; 
                 border: 1px solid #808080; 
                 line-height: 1.5;
                 padding: 2px;}
    span.insert {color: #e02427;
                 background-color: lavender;
                 font-size: 150%; 
                 margin: 0 3px; 
                 border: 1px solid #808080; 
                 line-height: 1.5;
                 padding: 2px;}
    span.parenthesis {color: #324ea8;
                    font-size: 100%;
                    margin: 0 3px;}
    </style>玉椀來回部, 輸誠供闔閶, 召公懷不寶, 韓子戒無當,異致白毛鹿, 引恬頳尾魴 <span class="parenthesis">(回部葉爾奇木哈什哈爾初役屬於準噶爾,為所拘縶,因我大軍戡定伊犁,始釋之令歸所部,其長伯克和卓遣使求內屬,此其所貢也)</span>, 勞徠非力并, 天眷奉昭彰.</p>
<p>玉盤博徑得二尺,圍六尺有<span class="parenthesis">(去聲)</span>五寸益.虛中盛水受一石,素質不雕其色碧. 旁達孚尹瓊華澤,葆光撫不留手跡.<span class="delete">群</span><span class="insert">羣</span>玉之精出<span class="delete">昆侖</span><span class="insert">菎崙</span>,吉日甲子天子賓. <span class="delete">於</span><span class="insert">于</span>西王母<span class="delete">瑤</span><span class="insert">瑶</span>池津,行觴 <span class="parenthesis">(I just ,added in a test, parenthesis here)</span> 介紹簠<span class="delete">蓋樽</span><span class="insert">簋罇</span>.爾時所御器今存,作鎮西極永好完. 未入震旦三千年,問今何來不脛偶.準噶爾亡淪世守,阿睦撒納茲竊取. 王師<span class="delete">深</span><span class="insert">罙</span>入靖孽醜,於將獲之<span class="delete">聯</span><span class="insert">聮</span>猭走.棄其重器為我有,元英大呂陳座右. 咄哉玉盤徒華滋,不可食兮不可衣.連城價詎如窮奇,俘彼禍除可罷師 <span class="parenthesis">(and another one was added here)</span>. 前歌後舞樂雍熙,<span class="delete">瑰</span><span class="insert">瓌</span>玩吾將安用之.擬付剿人一例椎.</p>
<p><span class="parenthesis">(did this work?)</span> 于闐何必購奩環,通貢薄來每厚還,.保定不期致<span class="delete">達</span><span class="insert">遠</span>域,琢磨亦復藉他山.示禎碧落星辰表,延喜明廷樽俎<span class="delete">問</span>,<span class="insert">間</span>.漉雪浮香真恰當,思推解渴福區寰. <span class="parenthesis">(maybe?)</span></p>
<p>會未于闐遣使求,堅昆玉椀自來投,詎云有翼千斤獻,那肯無端大白浮.賢問乃明君子德,工言幾誤楚人璆,歲時宴饗斟香茗,延喜明廷弈葉庥 <span class="parenthesis">(yes!)</span>.</p>

</div>

</div>

</div>

</div>  
logo: Jade001_Images/Jade001_NPMT_front.jpg


